######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 20 16:03:35 2011
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clickableqlabel.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += clickableqlabel.cpp main.cpp mainwindow.cpp
RESOURCES += images.qrc
